language: php

sudo: false

matrix:
  include:
    - php: 5.5
      env: WITH_LOWEST=true
    - php: 5.5
      env: WITH_HIGHEST=true
    - php: 5.6
      env: WITH_LOWEST=true
    - php: 5.6
      env: WITH_HIGHEST=true
    - php: 7.0
      env: WITH_LOWEST=true
    - php: 7.0
      env: WITH_HIGHEST=true
    - php: 7.1
      env: WITH_LOWEST=true
    - php: 7.1
      env: WITH_HIGHEST=true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer validate

install:
  - if [[ "$WITH_LOWEST" == "true" ]]; then composer update --prefer-lowest --prefer-dist; else composer install --prefer-dist; fi

before_script:
  - git config --global user.email "travis-ci@codeclimate.com"
  - git config --global user.name "Travis CI"

script:
  - vendor/bin/phpunit --coverage-clover=build/logs/clover.xml

after_script:
  - php composer/bin/test-reporter
